### ISSUE TITLE
Error: Text strings must be rendered within a <Text> component

### ISSUE THREAD

**Issue by yarin177** [harshzalavadiya/react-multi-select-component#138] opened 2020-09-15 18:46 UTC
I tried to use the basic demo to show a simple multiselect however I get this weird error not sure why I copied exactly like the demo code.

```
const options = [
    { label: "1/2", value: "1/2" },
    { label: "1/3", value: "1/3" },
    { label: "1/4", value: "1/4"},
    { label: "1/5", value: "1/5" },
    { label: "1/6", value: "1/6" },
    { label: "1/7", value: "1/7" },
    { label: "1/8", value: "1/8" },
  ];
const [selected, setSelected] = useState([]);
```

```
return (
      <div><pre>{JSON.stringify(selected)}</pre>
      <MultiSelect
        options={options}
        value={selected}
        onChange={setSelected}
        labelledBy={"Select"}
      />
    </div>

);
```

**Comment by harshzalavadiya** [comment] 2020-09-16 16:04
@yarin177,

Can you reproduce in codesandbox?
It looks like this is maybe related to react-native/expo thing

**Comment by harshzalavadiya** [comment] 2020-10-06 17:48
Closing due to no reponse

**Closed by harshzalavadiya** 2020-10-06 17:48 UTC
