### ISSUE TITLE
Non-null assertions can only be used in TypeScript files. while building the project

### ISSUE THREAD

**Issue by prashantup1993** [harshzalavadiya/react-multi-select-component#84] opened 2020-08-03 07:50 UTC
hi when i am uploading my project to pro env it's showing Non-null assertions can only be used in TypeScript files. while building the project , Can you help me in this?

**Comment by harshzalavadiya** [comment] 2020-08-03 08:03
@prashantup1993 

Can you create codesandbox reproduction?

**Comment by harshzalavadiya** [comment] 2020-08-27 06:53
closing due to no reproduction

**Closed by harshzalavadiya** 2020-08-27 06:53 UTC
